#pragma once

#include "nikola/nikola_gfx.h"

inline nikola::GfxShaderDesc generate_blinn_phong_shader() {
  return nikola::GfxShaderDesc {
    "#version 460 core"
    "\n"
    "layout (location = 0) in vec3 aPos;"
    "layout (location = 1) in vec3 aNormal;"
    "layout (location = 2) in vec2 aTextureCoords;"
    "\n"
    "out VS_OUT {"
    "  vec2 tex_coords;"
    "  vec3 normal;"
    "  vec3 pixel_pos;"
    "} vs_out;"
    "\n"
    "layout (std140, binding = 0) uniform Matrices {"
    "  mat4 u_view;"
    "  mat4 u_projection;"
    "};"
    "\n"
    "uniform mat4 u_model;"
    "uniform vec2 u_screen_size;"
    "\n"
    "void main() {"
    "  vec4 model_space = u_model * vec4(aPos, 1.0f);"
    "\n"
    "  vs_out.tex_coords = aTextureCoords;"
    "  vs_out.normal     = mat3(transpose(inverse(u_model))) * aNormal; "
    "  vs_out.pixel_pos  = vec3(model_space);"
    "\n"
    "  gl_Position       = u_projection * u_view * model_space;"
    "}",

    "#version 460 core"
    "\n"
    "layout (location = 0) out vec4 frag_color;"
    "\n"
    "in VS_OUT {"
    "  vec2 tex_coords;"
    "  vec3 normal;" 
    "  vec3 pixel_pos;"
    "} fs_in;"
    "\n"
    "struct Material {"
    "  sampler2D diffuse_map;"
    "  sampler2D specular_map;"
    "\n"
    "  float shininess;"
    "};"
    "\n"
    "struct DirectionalLight {"
    "  vec3 direction;" 
    "\n"
    "  vec3 ambient;" 
    "  vec3 diffuse;" 
    "  vec3 specular;" 
    "};"
    "\n"
    "struct PointLight {"
    "  vec3 position;" 
    "  vec3 direction;" 
    "\n"
    "  vec3 ambient;" 
    "  vec3 diffuse;"
    "  vec3 specular;" 
    "\n"
    "  float linear;"
    "  float quadratic;"
    "};"
    "\n"
    "uniform Material u_material;"
    "uniform DirectionalLight u_dir_light;"
    "uniform PointLight u_point_light;"
    "uniform vec3 u_view_pos;"
    "\n"
    "vec3 directional_light(DirectionalLight light);"
    "vec3 point_light(PointLight light);"
    "vec3 spot_light();"
    "\n"
    "void main() {"
    "  frag_color = vec4(point_light(u_point_light) + directional_light(u_dir_light), 1.0);"
    "}"
    "\n"
    "vec3 directional_light(DirectionalLight light) {"
    "  vec4 diffuse_texel  = texture(u_material.diffuse_map, fs_in.tex_coords);"
    "  vec4 specular_texel = texture(u_material.specular_map, fs_in.tex_coords);"
    "\n"
    "  vec3 ambient = light.ambient * vec3(diffuse_texel);"
    "\n"
    "  vec3 norm      = normalize(fs_in.normal);"
    "  vec3 light_dir = normalize(-light.direction);"
    "  float diff     = max(dot(norm, light_dir), 0.0);"
    "  vec3 diffuse   = diff * vec3(diffuse_texel) * light.diffuse;"
    "\n"
    "  // vec3 view_dir    = normalize(u_view_pos - fs_in.pixel_pos);"
    "  // vec3 reflect_dir = reflect(-light_dir, norm);"
    "  // float spec       = pow(max(dot(view_dir, reflect_dir), 0.0), u_material.shininess);"
    "  // vec3 specular    = light.specular * spec * vec3(specular_texel);"
    "\n"
    "  return ambient + diffuse;"
    "}"
    "\n"
    "vec3 point_light(PointLight light) {"
    "  vec4 diffuse_texel  = texture(u_material.diffuse_map, fs_in.tex_coords);"
    "  vec4 specular_texel = texture(u_material.specular_map, fs_in.tex_coords);"
    "\n"
    "  vec3 ambient = light.ambient * vec3(diffuse_texel);"
    "\n"
    "  vec3 norm      = normalize(fs_in.normal);"
    "  vec3 light_dir = normalize(light.position - fs_in.pixel_pos);"
    "  float diff     = max(dot(norm, light_dir), 0.0);"
    "  vec3 diffuse   = diff * vec3(diffuse_texel) * light.diffuse;"
    "\n"
    "  // Specular" 
    "  // vec3 view_dir    = normalize(u_view_pos - fs_in.pixel_pos);"
    "  // vec3 reflect_dir = reflect(-light_dir, norm);"
    "  // float spec       = pow(max(dot(view_dir, reflect_dir), 0.0), u_material.shininess);"
    "  // vec3 specular    = u_light.specular * spec * vec3(specular_texel);"
    "\n"
    "  float distance = length(light.position - fs_in.pixel_pos);"
    "  float atten    = 1.0 / (1.0 + light.linear * distance + light.quadratic * (distance * distance));"
    "\n"
    "  ambient *= atten;"
    "  diffuse *= atten;"
    "\n"
    "  return ambient + diffuse;"
    "}"
    "\n"
    "vec3 spot_light() {"
    "  return vec3(0.0);"
    "}"
  };
};
